version: "3.9"
services:
  backend:
    build: ./backend
    depends_on:
      - database
    env_file:
      - .env
    command: ["fastapi", "run", "./src/app.py"]
    ports:
      - "8000:8000"

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres-docker-entry:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
