version: "1.0"
services:
  backend:
    build: ./backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    command: ["fastapi", "run", "./src/app.py"]
    ports:
      - "8000:8000"

  database:
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

volumes:
  db: {}