version: "3.9"
services:
  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
      - database
    env_file:
      - .env
    ports:
      - "5173:5173"

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres-docker-entry:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5432/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
