version: "1.0"
services:
  backend:
    image: backend
    build: ./backend
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

volumes:
  db